2024-11-25 22:39:48,890 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.100.116:5002
2024-11-25 22:39:48,892 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-11-25 22:39:48,895 - werkzeug - INFO -  * Restarting with stat
2024-11-25 22:39:50,708 - werkzeug - WARNING -  * Debugger is active!
2024-11-25 22:39:50,717 - werkzeug - INFO -  * Debugger PIN: 637-608-658
2024-11-25 22:40:57,791 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:40:57,801 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:40:57,805 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:40:57] "[35m[1mGET /storage/ HTTP/1.1[0m" 500 -
2024-11-25 22:41:16,357 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:41:16,360 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:41:16,362 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:41:16,367 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:41:16,371 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:41:16,373 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:41:16,378 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:41:16] "[35m[1mGET /static/dataclient/user_admin4/data/Adu111111/NIK_7408.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:41:16,378 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:41:16,379 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:41:16,380 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:41:16,381 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:41:16,383 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:41:16] "[35m[1mGET /static/dataclient/user_admin4/data/Khách%20hường/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:41:16,387 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:41:16] "[35m[1mGET /static/dataclient/user_admin4/data/Adu/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:41:16,391 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:41:16] "[35m[1mGET /static/dataclient/user_admin4/data/té/DSC_8242.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:41:16,395 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:41:16] "[35m[1mGET /static/dataclient/user_admin4/data/T/NIK_7470.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:28,284 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:28,290 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:28,295 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:28] "[35m[1mGET /static/dataclient/user_admin4/data/Adu/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:28,295 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:28,319 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:28,324 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:28] "[35m[1mGET /static/dataclient/user_admin4/data/Adu111111/NIK_7408.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:28,355 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:28,358 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:28,365 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:28] "[35m[1mGET /static/dataclient/user_admin4/data/Khách%20hường/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:28,375 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:28,384 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:28,386 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:28,390 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:28,394 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:28] "[35m[1mGET /static/dataclient/user_admin4/data/T/NIK_7470.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:28,400 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:28] "[35m[1mGET /static/dataclient/user_admin4/data/té/DSC_8242.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:38,628 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:38,630 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:38,636 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:38] "[35m[1mGET /static/dataclient/user_admin4/data/Adu/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:38,641 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:38,645 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:38,650 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:38,651 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:38] "[35m[1mGET /static/dataclient/user_admin4/data/Adu111111/NIK_7408.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:38,654 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:38,660 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:38] "[35m[1mGET /static/dataclient/user_admin4/data/Khách%20hường/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:38,671 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:38,676 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:38,682 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:38] "[35m[1mGET /static/dataclient/user_admin4/data/T/NIK_7470.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:38,683 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:38,687 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:38,691 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:38] "[35m[1mGET /static/dataclient/user_admin4/data/té/DSC_8242.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:42,705 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:42,709 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:42,709 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:42,713 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:42,715 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:42] "[35m[1mGET /static/dataclient/user_admin4/data/Adu/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:42,715 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:42,718 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:42] "[35m[1mGET /static/dataclient/user_admin4/data/Adu111111/NIK_7408.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:42,723 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:42,726 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:42,727 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:42,731 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:42,733 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:42,734 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:42] "[35m[1mGET /static/dataclient/user_admin4/data/Khách%20hường/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:42,738 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:42] "[35m[1mGET /static/dataclient/user_admin4/data/té/DSC_8242.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:42,741 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:42] "[35m[1mGET /static/dataclient/user_admin4/data/T/NIK_7470.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:45,546 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:45,547 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:45,549 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:45,552 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:45,553 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:45,555 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:45] "[35m[1mGET /static/dataclient/user_admin4/data/Adu/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:45,557 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:45,558 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:45,560 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:45] "[35m[1mGET /static/dataclient/user_admin4/data/Adu111111/NIK_7408.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:45,563 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-25 22:45:45,565 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:45,568 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:45] "[35m[1mGET /static/dataclient/user_admin4/data/Khách%20hường/DSC_8343.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:45,572 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-25 22:45:45,574 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:45] "[35m[1mGET /static/dataclient/user_admin4/data/T/NIK_7470.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:45:45,579 - werkzeug - INFO - 127.0.0.1 - - [25/Nov/2024 22:45:45] "[35m[1mGET /static/dataclient/user_admin4/data/té/DSC_8242.JPG HTTP/1.1[0m" 500 -
2024-11-25 22:46:45,421 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-25 23:11:55,218 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.100.116:5002
2024-11-25 23:11:55,218 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-11-25 23:11:55,222 - werkzeug - INFO -  * Restarting with stat
2024-11-25 23:11:56,178 - werkzeug - WARNING -  * Debugger is active!
2024-11-25 23:11:56,199 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-25 23:21:50,936 - __main__ - INFO - Shutting down server...
2024-11-25 23:21:51,066 - __main__ - INFO - Shutting down server...
2024-11-26 16:56:13,836 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.100.116:5002
2024-11-26 16:56:13,837 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-11-26 16:56:13,841 - werkzeug - INFO -  * Restarting with stat
2024-11-26 16:56:14,469 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 16:56:14,478 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 16:59:28,312 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 16:59:28,394 - werkzeug - INFO -  * Restarting with stat
2024-11-26 16:59:29,975 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 16:59:29,984 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 16:59:48,695 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 16:59:48,766 - werkzeug - INFO -  * Restarting with stat
2024-11-26 16:59:49,397 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 16:59:49,405 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:00:06,306 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:00:06,388 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:00:06,989 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:00:06,999 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:01:18,993 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:01:19,066 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:01:19,970 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:01:19,980 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:09:20,995 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:09:21,062 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:09:21,969 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:09:21,977 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:11:30,884 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:11:30,962 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:11:31,912 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:11:31,921 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:15:17,472 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:15:17,576 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:15:18,303 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:15:18,313 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:15:57,211 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:15:57,293 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:15:58,201 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:15:58,213 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:21:30,469 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:21:30,535 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:21:31,431 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:21:31,440 - werkzeug - INFO -  * Debugger PIN: 708-803-016
2024-11-26 17:22:51,471 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:22:51] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:22:52,628 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:22:52] "GET / HTTP/1.1" 200 -
2024-11-26 17:24:04,759 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:24:04] "GET / HTTP/1.1" 200 -
2024-11-26 17:24:12,339 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:24:12] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:24:28,513 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:24:28] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:25:19,749 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:25:19,757 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:25:19,757 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:25:19] "[35m[1mGET /api/shares HTTP/1.1[0m" 500 -
2024-11-26 17:25:39,644 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:25:39,651 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:25:39,651 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:25:39] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:26:01,608 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:26:01,608 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:26:01,609 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:01] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:26:09,267 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:26:09,268 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:26:09,269 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:09] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:26:11,719 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:26:11,720 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:26:11,720 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:11] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:26:22,589 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:22] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:26:22,635 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:26:22,635 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:26:22,636 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:22] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:26:22,854 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:22] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:26:22,872 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:26:22,873 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:26:22,873 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:22] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:26:26,662 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:26] "[33mGET /api/albums/Aa/photos?username=admin4 HTTP/1.1[0m" 404 -
2024-11-26 17:26:27,145 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:26:27] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:27:19,032 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:27:19] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:27:19,079 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:27:19,080 - __main__ - ERROR - Traceback (most recent call last):
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:27:19,082 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:27:19] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:29:52,683 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:30:31,211 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.100.116:5002
2024-11-26 17:30:31,212 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-11-26 17:30:31,216 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:30:32,918 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:30:32,930 - werkzeug - INFO -  * Debugger PIN: 637-608-658
2024-11-26 17:30:33,040 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:30:33] "GET / HTTP/1.1" 200 -
2024-11-26 17:30:37,078 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:30:37,082 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:30:37,088 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:30:37] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:30:55,083 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:30:55,084 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:30:55,087 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:30:55] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:31:18,358 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:31:18,361 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:31:18,365 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:31:18] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:34:44,122 - werkzeug - INFO -  * Detected change in 'K:\\New\\Nextjs\\photo-album-next\\pages\\api\\upload_album.py', reloading
2024-11-26 17:35:43,033 - werkzeug - INFO -  * Restarting with stat
2024-11-26 17:35:44,887 - werkzeug - WARNING -  * Debugger is active!
2024-11-26 17:35:44,896 - werkzeug - INFO -  * Debugger PIN: 637-608-658
2024-11-26 17:35:44,974 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:35:44] "GET / HTTP/1.1" 200 -
2024-11-26 17:35:45,005 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:35:45] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:35:45,052 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:35:45,058 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:35:45,062 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:35:45] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:35:48,974 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:35:48,976 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:35:48,978 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:35:48] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/cover.jpg HTTP/1.1[0m" 500 -
2024-11-26 17:36:51,639 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:36:51] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:39:42,100 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:39:42] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:39:42,119 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:39:42,120 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:39:42,124 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:39:42] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:40:22,612 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:40:22] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:40:22,668 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:40:22,670 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:40:22,673 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:40:22] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:40:53,799 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:40:53] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:40:53,836 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:40:53,845 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:40:53,848 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:40:53] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:41:07,845 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:41:07] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:41:07,898 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:41:07,900 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:41:07,904 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:41:07] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:46:43,672 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:46:43] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:46:43,695 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:46:43,697 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:46:43,701 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:46:43] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:46:43,939 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:46:43] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:46:43,964 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:46:43,966 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:46:43,970 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:46:43] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:47:15,310 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:47:15] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:47:15,359 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:47:15,361 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:47:15,364 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:47:15] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:47:45,169 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:47:45] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:47:45,202 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:47:45,204 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:47:45,209 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:47:45] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:52:01,905 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:52:01] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:52:01,957 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:52:01,958 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:52:01,961 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:52:01] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:52:07,011 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:52:07] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:52:07,055 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:52:07,056 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:52:07,060 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:52:07] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:54:37,557 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:54:37] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:54:37,580 - __main__ - ERROR - Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-26 17:54:37,581 - __main__ - ERROR - Traceback (most recent call last):
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 318, in send_static_file
    return send_from_directory(
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "c:\Users\Thuc\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2024-11-26 17:54:37,584 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:54:37] "[35m[1mGET /static/dataclient/user_admin4/data/Khách/NIK_6225.JPG HTTP/1.1[0m" 500 -
2024-11-26 17:56:42,010 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:56:42] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:56:42,277 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:56:42] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:57:07,437 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:57:07] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:57:22,125 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:57:22] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:57:22,389 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:57:22] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 17:57:36,358 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 17:57:36] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 18:01:25,788 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 18:01:25] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 18:01:34,233 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 18:01:34] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
2024-11-26 18:01:34,643 - werkzeug - INFO - 127.0.0.1 - - [26/Nov/2024 18:01:34] "GET /api/albums?username=admin4 HTTP/1.1" 200 -
